#!/bin/bash
 read host 
 read ip 
 vars= 
    
 while read oid val 
     do 
     if [ "$vars" = ""  ] 
     then 
        vars+="$oid = $val\n"
        else 
             vars+="$vars, $oid = $val\n"
        fi 
    done 

echo -ne "trap: $1 $host $ip $vars" | mail -s snmpTrap micheal
